application: lbi-caption-competition
version: 1
runtime: python
api_version: 1

handlers:

- url: /assets
  static_dir: assets

- url: /admin.*
  script: main.py
  login: admin

- url: /captions.*
  script: main.py
  login: admin

- url: .*
  script: main.py
